import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const footerDate = {
    navLinks: [
      { name: "Home", href: "/" },
      { name: "About", href: "about" },
      { name: "Contact Us", href: "contact" },
    ],
    socialLinks: [
      { name: "Instagram", href: "www.google.com" },
      { name: "Github", href: "www.google.com" },
      { name: "Twitter", href: "www.google.com" },
    ],
  };

  return (
    <html lang="en">
      <body className="text-white   bg-[url('../../public/bg.webp')] bg-cover bg-center flex flex-col justify-start min-h-screen">
        <Header />
        {children}
        <Footer navLinks={footerDate.navLinks} socialLinks={footerDate.socialLinks} />
      </body>
    </html>
  );
}
